export const GAME_CONSTANTS = {
  CODE_LENGTH: 6,
  MIN_PLAYERS_TO_START: 1,
  COUNTDOWN_SECONDS: 5,
  POSITION_UPDATE_INTERVAL_MS: 1000,
  ROUTE_CACHE_TTL_SECONDS: 300,
} as const;

export const PROXIMITY_THRESHOLDS = {
  NEAR: 100,
  VERY_CLOSE: 50,
  REACHED: 30,
} as const;
